### ISSUE TITLE
Splitting Main.gd

### ISSUE THREAD

**Issue by RamseyD** [CS3398-Titan-HelloWorld/RoombaAttack#66]
Split into three scripts called 
1- Runtime Script (timers, start/stop locations)
2-Interrupt Script (UI buttons, error handeling )
3-Feedback Script (Collisions or conditions )

**Comment by Bkelley3** [comment]
I'm splitting Main into 2 other scripts (Runtime and Interrupt) because we haven't implemented feedback for the main specifically
